Route /mcp/sse
    MCP-Tool-SSE "npx @playwright/mcp --executable-path /usr/bin/chromium-browser --headless --isolated" 60000 /mcp/sse
End

Route /mcp/streamable
    MCP-Tool-Streamable "npx @playwright/mcp --executable-path /usr/bin/chromium-browser --headless --isolated" 60000
End

Route /health_204
   No-Content
End
